[versions]
adventure = "4.26.1" # last v4 release, staying for java 8 support. v5 is ABI compatible so it's fine
netty = "4.2.15.Final" # latest paper uses this version

[libraries]
spigotApi = "org.spigotmc:spigot-api:1.8-R0.1-SNAPSHOT" # oldest release on spigot repo
viaversionApi = "com.viaversion:viaversion-api:5.11.0"

adventureApi = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventureTextSerializerGson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventureTextSerializerLegacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }

nettyBuffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
nettyHandler = { module = "io.netty:netty-handler", version.ref = "netty" }

[plugins]
kotlin = "org.jetbrains.kotlin.jvm:2.4.10"
shadow = "com.gradleup.shadow:9.6.1"
nmcpAggregation = "com.gradleup.nmcp.aggregation:1.6.1"

[bundles]
adventure = [ "adventureApi", "adventureTextSerializerGson", "adventureTextSerializerLegacy" ]
netty = [ "nettyBuffer", "nettyHandler" ]
